CREATE TABLE "GCG_3201_CRM_DOC_TEM"(
 "TDID" IDENTITY DEFAULT '0',
 "TEMPLATE_NAME" CHAR(100),
 "PATH" CHAR(150),
 "FILENAME" CHAR(50),
 "SECURITY_GROUP" CHAR(50),
 "USERID" INTEGER,
 "LASTMODIFIEDDT" DATETIME,
 UNIQUE ("TDID"));
